package cn.zerobot.chatsummary;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

public final class PreviewReportGenerator {
    private PreviewReportGenerator() {
    }

    public static void main(String[] args) throws Exception {
        Settings settings = new Settings();
        settings.setReportWidth(560);
        settings.setMinHotWordCount(2);
        settings.setTopUserLimit(12);
        settings.setHotWordLimit(70);

        ZoneId zoneId = SummaryText.resolveZone(settings.getTimeZone());
        LocalDateTime endTime = LocalDateTime.of(2026, 6, 6, 16, 0);
        ReportWindow window = new ReportWindow(
                endTime.minusHours(8).atZone(zoneId).toInstant(),
                endTime.atZone(zoneId).toInstant(),
                "预览样例：最近 8 小时"
        );

        List<RecordedMessage> messages = sampleMessages(zoneId, endTime.minusHours(8));
        ReportData data = new ReportAnalyzer(settings, zoneId)
                .analyze("10086", "ZeroBot 测试交流群", window, messages);
        BufferedImage image = new ReportRenderer(settings, zoneId).render(data);

        Path output = Path.of("build", "preview", "chat-summary-preview.png");
        Files.createDirectories(output.getParent());
        ImageIO.write(image, "png", output.toFile());
        System.out.println(output.toAbsolutePath().normalize());
    }

    private static List<RecordedMessage> sampleMessages(ZoneId zoneId, LocalDateTime start) {
        List<RecordedMessage> messages = new ArrayList<>();
        String[][] users = {
                {"1001", "小梦", "member"},
                {"1002", "Lance", "member"},
                {"1003", "mzh", "administrator"},
                {"1004", "小空", "member"},
                {"1005", "FrostNova", "member"},
                {"1006", "7zNano", "member"},
                {"1007", "夏天不长胖", "member"},
                {"1008", "DrawCat", "member"}
        };
        String[] texts = {
                "早，昨天那个 ZeroBot 群总结插件我看了一下，图片风格已经有报告感了",
                "我觉得热词词云要保留，AI 世界 生成 语音 draw 这些关键词很醒目",
                "部署的时候注意 JDK 21，不然 compileJava 会找不到 javac",
                "今天可以把命令注册补上，plugin.yml 里的 commands 要跟 registerCommand 对齐",
                "这个 long image 如果宽度 720 发群里应该刚好，手机上也能看清楚",
                "刚刚试了一下 @1002 的参数，最近 6 小时和今日都能解析",
                "图片里群奖项那块挺有意思，能不能再加一个表情包投手",
                "我支持，群友画像比纯摘要更有灵魂，像话题发动机和夜间在线",
                "世界生成器那段真的笑死，AI 一句话把需求变成了三个需求",
                "draw 的按钮如果以后做网页预览，可以直接点一下生成样张",
                "日志里看到生成路径在 build preview，这样不会污染仓库",
                "总结内容不要太官方，稍微像群里真的有人在复盘就行",
                "FrostNova 说的对，主要话题可以按热词聚类，别全靠流水账",
                "今天 15 点左右聊天最密集，活跃分布应该会有明显峰值",
                "我又发一张截图 [图片]，报告里面图片/表情统计应该会加一",
                "哈哈哈这个插件名字可以叫群聊体检报告，热度 100 有点燃",
                "权限节点 chat-summary.report 默认开放就行，后面再接权限插件",
                "小梦这几句可以进金句：把一团需求拆成一张能看的图",
                "如果摘要生成失败，回复错误文本就够了，别让群里一直等",
                "语音总结以后也可以做，先把文本报告打磨稳",
                "AI 不是重点，重点是群友都能一眼看懂今天聊了什么",
                "我看主要话题至少有三块：部署、命令注册、图片样式",
                "晚点可以加 OpenAI 摘要，但本地规则版先跑起来很实用",
                "ZeroBot 的插件模板已经不是模板了，现在像一个正经插件",
                "报告页底部 Generated by ZeroBot ChatSummary 这个可以留",
                "今天这个节奏还挺高，mzh 一直在补边界条件",
                "DrawCat: draw draw draw，给我看图，不要只讲代码",
                "收到，马上生成预览图，看看有没有文字挤在一起",
                "如果图片太长也没关系，群聊长图本来就是刷一刷看的",
                "世界 世界 世界，热词权重应该能顶上去",
                "生成 生成 生成，词云最好有层级感",
                "语音 draw AI ZeroBot，这几个英文词也应该进词云",
                "我觉得活跃用户条形图很好懂，排行榜一眼就能扫到",
                "互动关系如果没有 @，就按 5 分钟内接话算，这个设计不错",
                "今天先这样，生成图片看一眼效果再决定要不要调色"
        };

        for (int i = 0; i < 96; i++) {
            String[] user = users[i % users.length];
            String text = texts[i % texts.length];
            int minuteOffset = i * 5 + (i % 7) * 3;
            if (i > 62) {
                minuteOffset += 95;
            }
            int images = text.contains("[图片]") || i % 17 == 0 ? 1 : 0;
            int at = text.contains("@") ? 1 : 0;
            int faces = i % 9 == 0 ? 1 : 0;
            messages.add(new RecordedMessage(
                    "10086",
                    user[0],
                    user[1],
                    user[2],
                    text,
                    start.plusMinutes(minuteOffset).atZone(zoneId).toInstant(),
                    10_000L + i,
                    images,
                    at,
                    faces,
                    0
            ));
        }
        return messages;
    }
}
